export default function SandboxView({ onNavigate, onReset }) {
  return (
    <div className="view-stack sandbox-view">
      <div className="view-intro"><div><p className="eyebrow">DISCOVERY / UNRESTRICTED</p><h1>Break the rules on purpose.</h1><p>Sandbox mode keeps the full experiment surface open. Edit loci, change pressure, introduce mutation, clone specimens, and inspect every recorded consequence.</p></div><span className="sandbox-badge">NO GATE</span></div>
      <div className="sandbox-grid"><section className="sandbox-card"><span className="sandbox-index">A / 01</span><h2>Change the starting organism</h2><p>Select a specimen in the Lab, edit its alleles, or introduce a controlled mutation. The model will keep every resulting state valid.</p><button className="primary-control" type="button" onClick={() => onNavigate('genome')}>Open genome editor</button></section><section className="sandbox-card"><span className="sandbox-index">B / 02</span><h2>Change the environment</h2><p>Set temperature, food, and predation independently. There is no single best genome—only a context-dependent advantage.</p><button className="secondary-control" type="button" onClick={() => onNavigate('lab')}>Change conditions</button></section><section className="sandbox-card"><span className="sandbox-index">C / 03</span><h2>Make a new record</h2><p>Run, pause, compare, and save the state locally. Use the same seed later to reproduce the run exactly.</p><button className="secondary-control" type="button" onClick={() => onNavigate('evolution')}>Inspect history</button></section></div>
      <section className="sandbox-safety"><span className="section-label">SCOPE</span><p>This is a simplified educational genetics model. It does not model real nucleotide sequences, medical traits, or deterministic real-world outcomes. Reset the run whenever you want a clean dish.</p><button className="text-control" type="button" onClick={onReset}>Reset current run</button></section>
    </div>
  );
}
